# produces volume table
# can then be inserted into newSoundEngineDataTables.s

print("; generated by tools/volumeTable.py")
print("volumeTable:")

for _a in range(0x10):
  s = "    .db     "
  first = True
  for _b in range(0x10):
    if first:
      first = False
    else:
      s += ","
    a = _a # 0xf - _a
    b = _b # 0xf - _b
    vol = ((b * a) // 0xf)
    if vol == 0 and b > 0 and a > 0:
      vol = 1
    s += f"{vol:2}"
  print(s)